coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "mobile/test"
  - "backend/test"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/generated_*.dart"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
