name: Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: 'Monscolis Staging Environment'

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: monscolis-staging
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
          healthcheck: "https://monscolis-staging.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true

      - name: Build and Deploy Mobile App
        working-directory: ./mobile
        env:
          API_BASE_URL: https://monscolis-staging.herokuapp.com
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
        run: |
          flutter build apk --dart-define=ENVIRONMENT=staging
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --release-notes "Automated deployment to staging"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: 'Monscolis Production Environment'
    needs: [deploy-staging]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Backend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: monscolis-prod
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
          healthcheck: "https://monscolis-prod.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true

      - name: Build and Deploy Mobile App
        working-directory: ./mobile
        env:
          API_BASE_URL: https://monscolis-prod.herokuapp.com
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
        run: |
          flutter build apk --dart-define=ENVIRONMENT=production
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "production" \
            --release-notes "Automated deployment to production"
