name: Deploy

on:
  push:
    branches: [ master, develop ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment:
      name: Monscolis Staging Environment
      url: https://monscolis-staging.herokuapp.com
    
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Staging
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: monscolis-staging
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
          env_file: "./backend/.env.example"
        env:
          HD_NODE_ENV: staging
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HD_DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          HD_REDIS_URL: ${{ secrets.STAGING_REDIS_URL }}

      - name: Build and Deploy Mobile App (Staging)
        working-directory: ./mobile
        env:
          API_BASE_URL: https://monscolis-staging.herokuapp.com
        run: |
          flutter build apk --dart-define=ENVIRONMENT=staging
          
      - name: Upload to Firebase App Distribution (Staging)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: testers
          file: mobile/build/app/outputs/flutter-apk/app-release.apk

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: Monscolis Production Environment
      url: https://monscolis-prod.herokuapp.com
    needs: [deploy-staging]
    
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Production
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: monscolis-prod
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "backend"
          env_file: "./backend/.env.example"
        env:
          HD_NODE_ENV: production
          HD_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HD_DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          HD_REDIS_URL: ${{ secrets.PRODUCTION_REDIS_URL }}

      - name: Build and Deploy Mobile App (Production)
        working-directory: ./mobile
        env:
          API_BASE_URL: https://monscolis-prod.herokuapp.com
        run: |
          flutter build apk --dart-define=ENVIRONMENT=production
          
      - name: Upload to Firebase App Distribution (Production)
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
          groups: production
          file: mobile/build/app/outputs/flutter-apk/app-release.apk
