name: End-to-End Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: monscolis_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        npm ci
        npm install -g knex

    - name: Setup backend environment
      working-directory: ./backend
      run: |
        cp .env.example .env
        npm run migrate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/monscolis_test
        NODE_ENV: test

    - name: Start backend server
      working-directory: ./backend
      run: |
        npm start &
        sleep 10
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/monscolis_test
        NODE_ENV: test
        PORT: 3000
        REDIS_URL: redis://localhost:6379

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'
        channel: 'stable'
        cache: true

    - name: Install mobile dependencies
      working-directory: ./mobile
      run: |
        flutter pub get
        flutter config --no-analytics

    - name: Run E2E tests
      working-directory: ./mobile
      run: flutter test integration_test
      env:
        API_BASE_URL: http://localhost:3000

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          mobile/test-results/
          backend/test-results/
