name: Flutter CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.x'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: |
        flutter pub get
        flutter config --no-analytics

    - name: Check formatting
      run: dart format --set-exit-if-changed .

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: |
        flutter test --coverage
        flutter test integration_test

    - name: Run integration tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        profile: pixel_2
        script: cd mobile && flutter test integration_test/app_test.dart

    - name: Build APK
      run: flutter build apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: mobile/build/app/outputs/flutter-apk/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: release-apk

    - name: Deploy to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFile: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
        groups: testers
        file: app-release.apk
